package com.kh.example.exception1;

public class Run {
	public static void main(String[] args) {
		new CharacterMenu().menu();
		System.out.println("정상종료"); //try catch를 사용하면 정상종료가 됨.
	}
}
